apiVersion: v1
kind: Service
metadata:
  name: hbase-master
spec:
  clusterIP: None
  selector:
    app: hbase-master
  ports:
    - name: rpc
      port: 16000
    - name: http
      port: 16010
---
apiVersion: v1
kind: Pod
metadata:
  name: hbase-master
  labels:
    app: hbase-master  
spec:
  containers:
  - env:
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: HBASE_SERVER_TYPE
      value: master
    - name: HDFS_PATH
      value: hadoop-hdfs-master:9000
    - name: ZOOKEEPER_SERVICE_LIST
      value: zk-cs
    - name: ZOOKEEPER_PORT
      value: "2181"
    image: registry.docker.uih/library/leo-hbase:1.2.6.1
    imagePullPolicy: IfNotPresent
    name: hbase-master
    ports:
    - containerPort: 16000
      protocol: TCP
    - containerPort: 16010
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: hbase-region-1
spec:
  clusterIP: None
  selector:
    app: hbase-region-1
  ports:
    - name: rpc
      port: 16020
    - name: http
      port: 16030
---
apiVersion: v1
kind: Service
metadata:
  name: hbase-region-2
spec:
  clusterIP: None
  selector:
    app: hbase-region-2
  ports:
    - name: rpc
      port: 16020
    - name: http
      port: 16030
---
apiVersion: v1
kind: Service
metadata:
  name: hbase-region-3
spec:
  clusterIP: None
  selector:
    app: hbase-region-3
  ports:
    - name: rpc
      port: 16020
    - name: http
      port: 16030
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hbase-region-1
  name: hbase-region-1
spec:
  containers:
  - env:
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: HBASE_SERVER_TYPE
      value: regionserver
    - name: HDFS_PATH
      value: hadoop-hdfs-master:9000
    - name: ZOOKEEPER_SERVICE_LIST
      value: zk-cs
    - name: ZOOKEEPER_PORT
      value: "2181"
    image: registry.docker.uih/library/leo-hbase:1.2.6.1
    imagePullPolicy: IfNotPresent
    name: hbase-region-1
    ports:
    - containerPort: 16020
      protocol: TCP
    - containerPort: 16030
      protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hbase-region-2
  name: hbase-region-2
spec:
  containers:
  - env:
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: HBASE_SERVER_TYPE
      value: regionserver
    - name: HDFS_PATH
      value: hadoop-hdfs-master:9000
    - name: ZOOKEEPER_SERVICE_LIST
      value: zk-cs
    - name: ZOOKEEPER_PORT
      value: "2181"
    image: registry.docker.uih/library/leo-hbase:1.2.6.1
    imagePullPolicy: IfNotPresent
    name: hbase-region-2
    ports:
    - containerPort: 16020
      protocol: TCP
    - containerPort: 16030
      protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hbase-region-3
  name: hbase-region-3
spec:
  containers:
  - env:
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: HBASE_SERVER_TYPE
      value: regionserver
    - name: HDFS_PATH
      value: hadoop-hdfs-master:9000
    - name: ZOOKEEPER_SERVICE_LIST
      value: zk-cs
    - name: ZOOKEEPER_PORT
      value: "2181"
    image: registry.docker.uih/library/leo-hbase:1.2.6.1
    imagePullPolicy: IfNotPresent
    name: hbase-region-3
    ports:
    - containerPort: 16020
      protocol: TCP
    - containerPort: 16030
      protocol: TCP